services:
  main:
    build: .
    image: jupyter/mine
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/workspace
    secrets:
      - ssh_key

secrets:
  ssh_key:
    file: ~/.ssh/github
    