services:
  main:
    build: .
    volumes:
      - julia:/home/mambauser/.julia:rw
      - ./notebook:/home/mambauser/notebook
    ports:
      - 8888:8888
    secrets:
      - ssh_key

volumes:
  julia:
    external: true

secrets:
  ssh_key:
    file: ~/.ssh/github
