services:
  main:
    tty: true
    build: .
    image: notebook
    ports:
      - "8888:8888"
      # - "1234:1234"
    volumes:
      - ./notebook/:/home/docker/workspace
    secrets:
      - ssh_key

secrets:
  ssh_key:
    file: ~/.ssh/github
